version: "2.1"
services: 
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:12
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: jayylmao
      POSTGRES_PASSWORD: yeetus
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
  integration: 
    build:
      context: ./api
      dockerfile: Dockerfile.test
    depends_on:
      - redis
      - db
