version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: docker-images-v1
      - run: docker pull redis
      - run: docker pull postgres:12
      - run: docker pull node
      - save_cache:
          key: docker-images-v1
          paths:
            - /var/lib/docker/
      - run:
          name: Start container and verify it's working
          command: docker-compose -f docker-compose-test.yml run integration
