version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: docker-compose-test
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./run-test
workflows:
    build-and-test:
      jobs:
        - build-and-test
