FROM node

# Create app directory
RUN mkdir -p /usr/src/web
WORKDIR /usr/src/web

# Install dependencies
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn

# Bundle app source
COPY . ./

# Exports
EXPOSE 3000
CMD ["yarn", "watch"]
